#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
name: Minishift E2E
on: pull_request
jobs:
  minishift-e2e:
    name: Operator installer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Install chectl dependencies"
      run: yarn --skip-integrity-check
    - name: Install and start minishift OCP 3.11 cluster
      run: |
        sudo curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04 -o /usr/local/bin/docker-machine-driver-kvm
        sudo chmod +x /usr/local/bin/docker-machine-driver-kvm
        sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
        sudo apt install libvirt-bin qemu-kvm


        echo "======== Start to install minishift ========"
        curl -Lo minishift.tgz https://github.com/minishift/minishift/releases/download/v1.34.2/minishift-1.34.2-linux-amd64.tgz
        tar -xvf minishift.tgz --strip-components=1
        chmod +x ./minishift
        sudo mv ./minishift /usr/local/bin/minishift

        minishift start --memory=5500 --registry-mirror=https://quay.io
